### ISSUE TITLE
BU-base_schema import_BaseTypes schema imported in version 3.3

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/application-schemas#124]
# Change proposal description
The [BuildingsBase.xsd](https://inspire.ec.europa.eu/schemas/bu-base/4.0/BuildingsBase.xsd) is importing the [BaseTypes.xsd in version 3.3](https://inspire.ec.europa.eu/schemas/base/3.3/BaseTypes.xsd). Proposal is to import the [latest BaseTypes.xsd in version 4.0](https://inspire.ec.europa.eu/schemas/base/4.0/BaseTypes.xsd) instead.

## Issue faced
The latest BuildingBase schema is not using the latest BaseTypes schema

### Expected behaviour
The current version of a schema is using the current version of imported schemas

### Current behaviour
Not the latest version of the BaseTypes schema is imported.

## Proposed solution
Import the BaseTypes.xsd to BuildingsBase.xsd in version 4.0 instead in version 3.3

# Additional information

## Addressed schema
https://inspire.ec.europa.eu/schemas/bu-base/4.0/BuildingsBase.xsd

## Impact on INSPIRE TG / IR
No impact on TG/IR IMO.

## Change proposer
Johanna Ott, wetransform GmbH for Landesvermessung und Geobasisinformation Brandenburg

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,

sorry for the late reply.

For schemas for which no major update has been made, such as BuildingsBase, we have decided to keep the import of the old BaseTypes schema (i.e. version 3.3) so as not to break existing implementations due to the namespace change (from http://inspire.ec.europa.eu/schemas/base/3.3 to http://inspire.ec.europa.eu/schemas/base/4.0).

Since the BaseTypes schema defines the inspireId element, which is used by all schemas, updating the BaseTypes schema in all other schemas would have resulted in an error in all currently harmonized datasets.
Therefore even in datasets for which there has not been a change in the version of the relevant schema.

I hope this helps to clarify.

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,

I hope the provided explanation effectively addresses your change proposal and provides the clarity you need.

I will close the issue now, but please feel free to reopen it if you have any further comments.
