### ISSUE TITLE
US_Remove folder containing schemas not included in IR

### ISSUE THREAD

**Issue by fabiovin** [INSPIRE-MIF/application-schemas#37]
# Change proposal description
Remove the following folder https://inspire.ec.europa.eu/schemas/us-net-tc/ containing schemas not included in IR.

## Issue faced
The application schema _Telecommunications network_ is only proposed in the Technical guidance and it is not included in the Implementing Rules.
To be in line with the scope of the "official" schema repository -  _`contains only those data models that are contained in the amendment to the Implementing Rules for Annex II+III themes, including the updates of the Annex I data themes`_ - the application schema _Telecommunications network_ should not be present in the schema repository but only in the draft one.

## Proposed solution
Remove the folder from the _schema_ repository and move the content in the _draft-schema_ repository.

# Additional information

## Impact on INSPIRE TG / IR
No

**Comment by PalmJanssen** [comment]
Dear @fabiovin @heidivanparys,

Replacing or removing the telecom xsd has an impact on our operational data services.

In the Netherlands we run a cable and pipeline excavation damage data service based on INSPIRE data specs. The use of this service is **legally mandated**. The service uses the INSPIRE 4.0 xml schemas, for data specs and validation. It was noticed by operators that since nov 16 the telecom xsd was not available any more. This was communicated to Geonovum (the INSPIRE implementation coordinator and related cable and pipeline standerd office).

What to do now? Our most optimal solution is that the XSD is placed back again to its original URL. This would evade a lot of communication and onforseen complications.

kind regards,

Paul Janssen
Geonovum, Netherlands
