### ISSUE TITLE
MineralResources sourceReference problem

### ISSUE THREAD

**Issue by CLinGBA** [INSPIRE-MIF/application-schemas#41]
Dear all,
 
There seems to be an issue with EarthResource and the sourceReference element in MineralResources, defined in the UML as: sourceReference: DocumentCitation[1..*]
 
In the XSD, the reference to the DocumentCitation dataType gets lost (only mentioned in the appinfo tag), while the xlinks provided via the gml:AssociationAttributeGroup aren't of help as DocumentCitation is a dataType, thus cannot be referenced.
 
This is an issue, as we thus cannot provide this mandatory information. XSD Snippet showing the issue below

`<element name="sourceReference" nillable="true" maxOccurs="unbounded">
    <annotation>
        <documentation>-- Definition --
The source or reference for the Earth Resource.</documentation>
        <appinfo>
            <targetElement xmlns="http://www.opengis.net/gml/3.2">base2:DocumentCitation</targetElement>
        </appinfo>
    </annotation>
    <complexType>
        <complexContent>
            <extension base="gml:AbstractMemberType">
                <sequence/>
                <attributeGroup ref="gml:AssociationAttributeGroup"/>
            </extension>
        </complexContent>
    </complexType>
</element>`
 
Many thanks,
 
Christian

**Comment by KathiSchleidt** [comment]
MR_EarthResource_sourceReference_doesn't_link_to_DocumentCitation

# Change proposal description
Update the XSD so that the reference to the DocumentCitation dataType is contained in sourceReference of EarthResource and derived types as foreseen in the UML model

## Issue faced
As the sequence provided under sourceReference doesn't contain DocumentCitation, this information cannot be provided inline. 
In the XSD, there is a gml:AssociationAttributeGroup providing xlinks, however, DocumentCitation is a dataType, thus cannot be referenced. 
As sourceReference is mandatory, this means it is not possible to provide valid data in featureTypes based on EarthResource 

### Expected behaviour
It should be possible to provide a DocumentCitation inline as foreseen by the model

### Current behaviour
It is not possible to provide a DocumentCitation inline as foreseen by the model

### Steps to reproduce
Try and provide EarthResource including sourceReference

## Proposed solution
Fix the empty sequence currently under sourceReference by adding DocumentCitation - currently just `<sequence/>`

### Technical details
`<element name="sourceReference" nillable="true" maxOccurs="unbounded"> 

    <annotation> 

        <documentation>-- Definition -- The source or reference for the Earth Resource.</documentation> 

        <appinfo> <targetElement xmlns="http://www.opengis.net/gml/3.2">base2:DocumentCitation</targetElement> </appinfo> 

    </annotation> 

    <complexType> 

        <complexContent> 

            <extension base="gml:AbstractMemberType"> 

                <sequence/> 

                <attributeGroup ref="gml:AssociationAttributeGroup"/> 

            </extension> 

        </complexContent> 

    </complexType> 

</element>`

# Additional information

## Proposal reason
This is a bug, and hinders provision of valid information utilizing the EarthResource featureType

## Addressed schema
MineralResources

## Impact on INSPIRE TG / IR
Makes it possible to fulfill the TG/IR Requirements

## Change proposer
Geologische Bundesanstalt (GBA) (Austrian Geological Agency), supported by DataCove e.U.

**Comment by sMorrone** [comment]
Dear @CLinGBA , @KathiSchleidt 
could one of you provide a pull request with changes to the schema? 
Thank you
Stefania

**Comment by KathiSchleidt** [comment]
Hiya,
now fixed the schema, replaced

```
<sequence minOccurs="0">
	<element ref="swe:Category"/>
</sequence>
```

with 

```
<sequence minOccurs="0">
	<element ref="base2:DocumentCitation"/>
</sequence>

```
Does the trick

**Comment by sMorrone** [comment]
@Kathi,
I think you meant you replaced   
`<sequence/>`
i.e the empty sequence tag with
```
<sequence minOccurs="0">
  <element ref="base2:DocumentCitation"/>
</sequence>
```
am I right?

**Comment by KathiSchleidt** [comment]
Sorry, my mistake! Thanks for the correction

**Comment by sMorrone** [comment]
Subgroup Meeting 15-12-2021: Change proposal is approved

**Comment by MarcoMinghini** [comment]
The INSPIRE CT approved the change proposal during today's meeting. In the next step, the proposal will be moved to the MIG for the final endorsement.

**Comment by sMorrone** [comment]
During the joint MIG/MIG-T meeting held on 31/03-01/04/2022, the proposal was endorsed.
More details in the meeting minutes on the [69th MIG-T meeting page](https://wikis.ec.europa.eu/display/InspireMIG/69th+MIG-T+meeting+2022-04-01)
