### ISSUE TITLE
TN-A_Nodes_inherit from TransportPoint instead of TransportNode

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/application-schemas#61]
# Change proposal description
The three feature types AerodromeNode, DesignatedPoint and RunwayCentrelinePoint should inherit from TransportPoint instead of TransportNode.

## Issue faced
The three types are currently inheriting from TransportNode. That means that they shall theoretically only be present where transport links connect or end. This is not the case in reality and the model should therefore be adapted.

### Expected behaviour
AerodromeNode, DesignatedPoint and RunwayCentrelinePoint inherit from TransportPoint

### Current behaviour
AerodromeNode, DesignatedPoint and RunwayCentrelinePoint inherit from TransportNode

# Additional information
More detailed in formation can be found in [this issue](https://github.com/INSPIRE-MIF/helpdesk/issues/62)

## Proposal reason
The current schema version does not fit specific use cases. See [this issue](https://github.com/INSPIRE-MIF/helpdesk/issues/62) for detailed explanations.

## Addressed schema
[TN-A](https://inspire.ec.europa.eu/schemas/tn-a/4.0/AirTransportNetwork.xsd)

## Impact on INSPIRE TG / IR
IR on interoperability
* 7.4.1.3. : "This type is a sub-type of TransportPoint"
* 7.4.1.13.: "This type is a sub-type of TransportPoint"
* 7.4.1.22.: "This type is a sub-type of TransportPoint"

TG TN
* UML diagrams
* 5.8.2.1.3: "Subtype of: TransportPoint"
* 5.8.2.1.13: "Subtype of: TransportPoint"
* 5.8.2.1.22: "Subtype of: TransportPoint"

## Change proposer
Johanna Ott, wetransform GmbH for DFS (Deutsche Flugsicherung)

### More detailed documentation
[GitHub issue](https://github.com/INSPIRE-MIF/helpdesk/issues/62)
[INSPIRE Forum](https://wayback.archive-it.org/12090/20210119213342/https://inspire.ec.europa.eu/forum/discussion/view/261634/tn-air-should-aerodromenode-be-a-transportnode-or-a-transportpoint)

**Comment by fabiovinci** [comment]
As shown in the figure below the three feature types _AerodromeNode_, _DesignatedPoint_ and _RunwayCentrelinePoint_ are sub-type of the feature type _AirNode_ (Definition: A node which occurs in an air network), which in turn is a sub-type of the feature type _TransportNode_ (Definition: A point spatial object which is used for **connectivity**).

![image](https://user-images.githubusercontent.com/22212406/158342740-f02ef234-b2fd-4a40-8f3c-c5a1afd32ee3.png)

The feature type _TransportNode_ is, in turn, a sub-type of the feature type _Node_ (Definition: Represents a significant position in the network that **always occurs at the beginning or the end of a link**), so the three feature types _AerodromeNode_, _DesignatedPoint_ and _RunwayCentrelinePoint_ inherit the constraint that those points shall occur at the beginning or the end of a link.

![image](https://user-images.githubusercontent.com/22212406/158345987-4b904d3a-751c-4cf8-a907-fc563ecee107.png)

Since this does not seem the case for the three spatial objects in question, the most appropriate feature type of which they should be sub-types is _TransportPoint_ (Definition: A point spatial object - **which is not a node** - that represents the position of an element of a transport network).

![image](https://user-images.githubusercontent.com/22212406/158346081-7428993e-7818-4832-933a-590ccde67fd1.png)

**Comment by sMorrone** [comment]
Subgroup meeting on 13.09.2022:
necessary thematic support is still missing.  For the evaluation of this change proposal, therefore, the sub-group has decided to ask  the MIG-T to approach transportation experts at the national level and ask them to provide feedback directly as comments to this GitHub issue, if possible.

**Comment by VeronikaKusova** [comment]
Hi all,
Two things came to my mind regarding this issue:
1.	Why TouchDownLiftOff is not included in this change? Isn’t it the same case? (And I do not know anything about Navaid. So, may be also the same case?)
2.	When AirRouteLinks are provided, they should start and end with nodes. How will this situation be handled? Because it seems to me, there will not be any features representing nodes (according to the proposal). Or am I wrong?

Thank you for the clarification.

**Comment by fabiovinci** [comment]
Dear @VeronikaKusova,

thank you for your contribution.
Regarding your questions:

1. It could be the case that the other two feature types (_TouchDownLiftOff_ and _Navaid_) are in the same situation, i.e. they are not nodes but simple points (let's wait for transportation experts' feedback).
2. Should all five feature types not be generalizations of the _AirNode_ feature type, there will be no possibility to provide "nodes" for the AirRouteLinks, since the _AirNode_ feature type is abstract. In this case, in order to provide nodes, one could e.g. remove the abstract property for the _AirNode_ feature type or specialize it by one or more new feature types.

**Comment by sMorrone** [comment]
Dear all,
in the context of the END reporting, a [discussion](https://github.com/INSPIRE-MIF/helpdesk/discussions/146) on how to provide major airport sources (only point geometry, no transport link information) under INSPIRE TN led to the proposal below which is relevant to issue being discussed here. 

The proposal is based on the use the AerodromeNode with ‘significantPoint’ set to false.
Copy/pasting from the discussion:

The significantPoint is an attribute of the AerodromeNode “_which indicates whether the air node is or is not a significant point_” i.e., _a specified geographical location used to define an ATS route, the flight path of an aircraft or for other navigation/ATS purposes_.
The AerodromeNode could either simply represent the aerodrome location (**significantPoint = false**) or act as transport node for connectivity (**significantPoint = true**). 
**Transport links should be mandatory only when significantPoint is set to true.**

This option would not require a change in the IR  /in the UML model, but only a clarification note in the TG (and a related change in the INSPIRE Validator test).

What do you think? Could this be a viable solution to the faced issue of this change proposal?

**Comment by fabiovinci** [comment]
The INSPIRE MIG-T approved the change proposal during the [74th MIG-T meeting](https://wikis.ec.europa.eu/display/InspireMIG/74th+MIG-T+meeting+2023-04-28). The proposal will be moved to the MIG for the final endorsement.

**Comment by sMorrone** [comment]
As no objections were raised by MIG members within the two-week window, the proposal is endorsed.

**Comment by sMorrone** [comment]
The endorsed proposal does not require any schema changes, but only the addition of a clarification note in the TG and a related change in the behaviour of the INSPIRE Validator. Therefore, this change request will now be closed. For documentation purposes, a corresponding new issue (labelled as 'endorsed') will be opened in the TG repository.
